name: Prevent Secrets Push

on: [push, pull_request]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scan for connection strings
        run: |
          if git grep -Ei 'Server=|Database=|User Id=|Password=' -- '*.cs' '*.json' '*.config'; then
            echo "❌ Push rejected! Connection string detected."
            exit 1
          fi
